### ISSUE TITLE
issue with building pigweed on windows 

### ISSUE THREAD

**Issue by HusseinElsherbini** [google/pigweed#8]
FAILED: python/gen/matter_build_venv._create_virtualenv.pw_pystamp
C:/Users/Hae14/Desktop/matter-4/.environment/cipd/packages/python/bin/python3.exe ../../third_party/pigweed/repo/pw_build/py/pw_build/python_runner.py --gn-root ../../ --current-path ../.. --default-toolchain=//build/toolchain/host:win_x64_gcc --current-toolchain=//third_party/pigweed/repo/pw_build/python_toolchain:python --touch python/gen/matter_build_venv._create_virtualenv.pw_pystamp --capture-output --python-dep-list-files python/gen/matter_build_venv._create_virtualenv_metadata_path_list.txt -- ../../third_party/pigweed/repo/pw_build/py/pw_build/create_gn_venv.py --destination-dir python-venv
Traceback (most recent call last):
  File "C:\Users\Hae14\Desktop\matter-4\third_party\pigweed\repo\pw_build\py\pw_build\create_gn_venv.py", line 38, in <module>
    main(**vars(_parse_args()))
  File "C:\Users\Hae14\Desktop\matter-4\third_party\pigweed\repo\pw_build\py\pw_build\create_gn_venv.py", line 34, in main
    venv.create(destination_dir, symlinks=use_symlinks, with_pip=True)
  File "C:\Users\Hae14\Desktop\matter-4\.environment\cipd\packages\python\bin\lib\venv\__init__.py", line 412, in create
    builder.create(env_dir)
  File "C:\Users\Hae14\Desktop\matter-4\.environment\cipd\packages\python\bin\lib\venv\__init__.py", line 75, in create
    self._setup_pip(context)
  File "C:\Users\Hae14\Desktop\matter-4\.environment\cipd\packages\python\bin\lib\venv\__init__.py", line 298, in _setup_pip
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "C:\Users\Hae14\Desktop\matter-4\.environment\cipd\packages\python\bin\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\Hae14\Desktop\matter-4\.environment\cipd\packages\python\bin\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Hae14\Desktop\matter-4\.environment\cipd\packages\python\bin\lib\subprocess.py", line 951, in __init__

    self._execute_child(args, executable, preexec_fn, close_fds,

  File "C:\Users\Hae14\Desktop\matter-4\.environment\cipd\packages\python\bin\lib\subprocess.py", line 1420, in _execute_child

    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,

FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by HusseinElsherbini** [comment]
??
